### PR TITLE
Add support for [build-dependencies] section

### PR DESCRIPTION
**Pull request by mbuesch**
Example:

```
[build-dependencies]
autocfg = "1.0.0"
```

### CODE REVIEW

**Comment by mbuesch** [comment]
The diff that Github shows is a little bit convoluted.
If you look at the whitespace-cleaned diff, it's much clearer what has been changed:
`git diff -w`

**Comment by mbuesch** [comment]
As a nice side effect, this change also fixes an unwrap() crash that happens, if there's neither a [dependencies] nor a [build-dependencies] section in the Cargo.toml.

**Comment by mbuesch** [comment]
Gentle poke :)

**Comment by RoffelKartoffel** [comment]
Thank you for your patience. :) Looks fine to me.

**Pull request merged**
