### PR TITLE
Add support for non-inline table notation

### PR DESCRIPTION
**Pull request by mbuesch**
This change adds support for the non-inline table notation.

Example Cargo.toml
```
[dependencies.toml_edit]
version = "0.1.3"
...
```

Without this change the program crashes if such a table is used in Cargo.toml.

### CODE REVIEW

**Comment by RoffelKartoffel** [comment]
Thank you for this report and fix.
I have not come across this syntax myself – is that a common thing? Does it conform the Cargo specification?
Thanks in advance :)

**Comment by mbuesch** [comment]
Yes, I think this is standard. See e.g.
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#choosing-features

I use it in one of my projects. That's how I noticed.

**Comment by mbuesch** [comment]
Any news about this?

**Comment by RoffelKartoffel** [comment]
Finally had some time to look into your patch and it looks good to me. Are there already more follow up patches form your side in the pipeline? :)

**Comment by mbuesch** [comment]
Great. Thanks for merging.

Yes, there are a couple of other changes, that I need for my projects:

- support for build-dependencies updates
- (optional?) ignore beta and rc versions
- support for dependencies with build conditions

Example for a dependency with build conditions:
```
[target.'cfg(target_os="windows")'.dependencies]                                                                                                       
winapi          = "0.3.0"
```

I'll start with build-dependencies and send you a pull.

**Pull request merged**
